### ISSUE TITLE
偶见在后台内存爆栈

### ISSUE THREAD

**Issue by sisel** [pengjinning/AppKeFu_Android_Demo_V4#2]
```
W/art: Large object allocation failed: Failed anonymous mmap(0x0, 20480, 0x3, 0x2, 30, 0): Operation not permitted. See process maps in the log.
W/libc: pthread_create failed: couldn't allocate 1069056-bytes mapped space: Out of memory
W/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"

W/System.err: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
W/System.err:     at java.lang.Thread.nativeCreate(Native Method)
W/System.err:     at java.lang.Thread.start(Thread.java:1063)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
W/System.err:     at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
W/System.err:     at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)
W/System.err:     at com.appkefu.smack.PacketReader.processPacket(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader.parsePackets(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader.access$000(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader$1.run(Unknown Source)
I/Process: Sending signal. PID: 4461 SIG: 9
```

机型 :一加一
系统 :cm13.1 已root

**Comment by sisel** [comment]
![image](https://cloud.githubusercontent.com/assets/11017062/20048488/ec00adb8-a4f7-11e6-8da5-b54750fb7779.png)
这是一个heap dump,
这3个对象有1800多个,请问是正常的吗?

**Comment by pengjinning** [comment]
多谢反馈!已转技术跟进,
另外:
是最新版的么?
如果不是, 建议升级最新版

2016-11-07 

pengjinning 

发件人：sisel notifications@github.com
发送时间：2016-11-07 14:36
主题：[pengjinning/AppKeFu_Android_Demo_V4] 偶见在后台内存爆栈 (#2)
收件人："pengjinning/AppKeFu_Android_Demo_V4"AppKeFu_Android_Demo_V4@noreply.github.com
抄送：

W/art: Large object allocation failed: Failed anonymous mmap(0x0, 20480, 0x3, 0x2, 30, 0): Operation not permitted. See process maps in the log.
W/libc: pthread_create failed: couldn't allocate 1069056-bytes mapped space: Out of memory
W/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"

W/System.err: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
W/System.err:     at java.lang.Thread.nativeCreate(Native Method)
W/System.err:     at java.lang.Thread.start(Thread.java:1063)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
W/System.err:     at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
W/System.err:     at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)
W/System.err:     at com.appkefu.smack.PacketReader.processPacket(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader.parsePackets(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader.access$000(Unknown Source)
W/System.err:     at com.appkefu.smack.PacketReader$1.run(Unknown Source)
I/Process: Sending signal. PID: 4461 SIG: 9

机型 :一加一
系统 :cm13.1 已root

**Comment by sisel** [comment]
4.20版,9/28的那个

**Comment by sisel** [comment]
找到一个可疑的泄露点:

```
public class ServiceDiscoveryManager {
    private static final String DEFAULT_IDENTITY_NAME = "Smack";
    private static final String DEFAULT_IDENTITY_CATEGORY = "client";
    private static final String DEFAULT_IDENTITY_TYPE = "pc";
    private static List identities = new LinkedList();
    private static Map instances = new ConcurrentHashMap();//<----此处
    private Connection connection;
```

静态map引用自身,自身引用connection从而无法释放

**Comment by pengjinning** [comment]
OK 多谢,
已转发技术

2016-11-07 

pengjinning 

发件人：sisel notifications@github.com
发送时间：2016-11-07 15:14
主题：Re: [pengjinning/AppKeFu_Android_Demo_V4] 偶见在后台内存爆栈 (#2)
收件人："pengjinning/AppKeFu_Android_Demo_V4"AppKeFu_Android_Demo_V4@noreply.github.com
抄送："jack ning"pengjinning@163.com,"Comment"comment@noreply.github.com

找到一个可疑的泄露点:
public class ServiceDiscoveryManager {
    private static final String DEFAULT_IDENTITY_NAME = "Smack";
    private static final String DEFAULT_IDENTITY_CATEGORY = "client";
    private static final String DEFAULT_IDENTITY_TYPE = "pc";
    private static List identities = new LinkedList();
    private static Map instances = new ConcurrentHashMap();//<----此处
    private Connection connection;

静态map引用自身,自身引用connection从而无法释放

**Comment by pengjinning** [comment]
问题已解决, 已升级,  请更新最新版本

**Comment by mabeijianxi** [comment]
可以请问下具体的技术解决方法吗，我现在的项目也遇到这个问题了

**Comment by pengjinning** [comment]
你是什么时候版本的? 最新版已经解决了哦, 建议用最新版jar包替换老版

2017-02-08 

pengjinning 



发件人：马北剑西 <notifications@github.com>
发送时间：2017-02-08 17:08
主题：Re: [pengjinning/AppKeFu_Android_Demo_V4] 偶见在后台内存爆栈 (#2)
收件人："pengjinning/AppKeFu_Android_Demo_V4"<AppKeFu_Android_Demo_V4@noreply.github.com>
抄送："jack ning"<pengjinning@163.com>,"State change"<state_change@noreply.github.com>

可以请问下具体的技术解决方法吗，我现在的项目也遇到这个问题了

**Comment by mabeijianxi** [comment]
我想请教下你们技术用什么方法解决的，改了什么东西呢，感谢

**Comment by pengjinning** [comment]
改了多个地方，其中主要地方是：使用单例模式代替重复分配对象
